# Generated by Django 4.2.7 on 2024-01-13 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='тело письма')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', related_query_name='mail', to=settings.AUTH_USER_MODEL, verbose_name='автор рассылки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_start', models.DateField(blank=True, null=True, verbose_name='начало рассылки')),
                ('mailing_end', models.DateField(blank=True, null=True, verbose_name='конец рассылки')),
                ('mailing_period', models.CharField(blank=True, choices=[('Ежедневно', 'Daily'), ('Еженедельно', 'Weekly'), ('Ежемесячно', 'Monthly')], max_length=12, null=True, verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('Черновик', 'Draft'), ('Создана', 'Created'), ('Запущена', 'Running'), ('Завершена', 'Completed')], default='draft', max_length=10, verbose_name='статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', related_query_name='setting', to='mailing.mailingmessage', verbose_name='рассылка')),
                ('recipient', models.ManyToManyField(related_name='clients', to='clients.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('mailing_start', 'mailing_end'),
            },
        ),
    ]
