# Generated by Django 4.2.7 on 2024-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Успешно', 'Success'), ('Неуспешно', 'Failed')], max_length=9, null=True, verbose_name='статус отправки')),
                ('message', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='время попытки')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('status',),
            },
        ),
    ]
