# Generated by Django 4.2.7 on 2024-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='recipient',
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='recipient',
            field=models.ManyToManyField(related_name='clients', to='clients.client', verbose_name='клиенты'),
        ),
    ]
