# Generated by Django 4.2.7 on 2024-01-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailingsettings_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='next_sending_date',
            field=models.DateField(blank=True, null=True, verbose_name='следующая отправка'),
        ),
    ]
