# Generated by Django 4.2.7 on 2024-01-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailinglog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'ordering': ('owner', 'is_published'), 'permissions': [('can_cancel_mailing', 'Может отменять публикацию рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ('mailing_start', 'mailing_end'), 'verbose_name': 'настройки рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликована'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_period',
            field=models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=12, null=True, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='draft', max_length=10, verbose_name='статус рассылки'),
        ),
    ]
