# Generated by Django 4.2.7 on 2024-01-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingsettings_next_sending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingmessage', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликована'),
        ),
    ]
