# Generated by Django 4.2.7 on 2024-01-13 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='контактный email')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleints', related_query_name='client', to=settings.AUTH_USER_MODEL, verbose_name='владелец списка рассылки')),
            ],
            options={
                'verbose_name': 'клиент рассылки',
                'verbose_name_plural': 'клиенты рассылки',
                'ordering': ('email',),
            },
        ),
    ]

